language: rust
rust: stable
os:
  - linux
cache:
  cargo: true
  directories:
    - $HOME/.kcov

env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-C link-dead-code"
    - CARGO_MAKE_KCOV_INSTALLATION_DIRECTORY=$HOME/.kcov

install:
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - which cargo-make || cargo install cargo-make
  - cargo fmt --all -- --check
  - cargo build
  - cargo test
  - cargo clippy --all-targets --all-features -- -D warnings
  - sudo /home/travis/.cargo/bin/cargo make --no-workspace workspace-coverage